name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build CV
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Compile
        shell: bash
        run: |
          make
          apt-get update
          apt-get install -y zip
          zip --junk-path cv.zip examples/*.pdf
      - name: Archive CV artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: |
            examples/*.pdf
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: cv.zip
